import type { AvatarDef } from "@/lib/avatars";

export const FIGHTER_CARD_META: Record<
  AvatarDef["id"],
  {
    type: string;
    hp: number;
    atk: number;
    spd: number;
    weird: number;
    rarity: "common" | "rare" | "legend";
    flavor: string;
    number: string;
  }
> = {
  skullmic: {
    type: "EAR · NIGHT",
    hp: 88,
    atk: 72,
    spd: 65,
    weird: 99,
    rarity: "legend",
    flavor: "Its ears hear screams from three cafeterias away.",
    number: "001",
  },
  skullbunny: {
    type: "HOP · DOOM",
    hp: 76,
    atk: 84,
    spd: 91,
    weird: 78,
    rarity: "rare",
    flavor: "Buck teeth carved from cafeteria tile shards.",
    number: "002",
  },
  gaperskull: {
    type: "GAP · VOID",
    hp: 94,
    atk: 58,
    spd: 42,
    weird: 100,
    rarity: "legend",
    flavor: "The jaw fell off during lunch and never came back.",
    number: "003",
  },
  wormface: {
    type: "WRM · ELDR",
    hp: 82,
    atk: 69,
    spd: 74,
    weird: 95,
    rarity: "rare",
    flavor: "Worms on its head whisper upgrade choices.",
    number: "004",
  },
  sporkfiend: {
    type: "UTN · SHIV",
    hp: 80,
    atk: 88,
    spd: 70,
    weird: 82,
    rarity: "rare",
    flavor: "Born when a spork and a nightmare shared a tray.",
    number: "005",
  },
  slurpghoul: {
    type: "SIP · COLD",
    hp: 74,
    atk: 62,
    spd: 86,
    weird: 88,
    rarity: "common",
    flavor: "Brain freeze became brain feast.",
    number: "006",
  },
  nachomancer: {
    type: "TRI · HEAT",
    hp: 86,
    atk: 79,
    spd: 55,
    weird: 91,
    rarity: "rare",
    flavor: "Casts cheese hexes in perfect triangular runes.",
    number: "007",
  },
  burgerlich: {
    type: "BN · KING",
    hp: 98,
    atk: 66,
    spd: 38,
    weird: 77,
    rarity: "legend",
    flavor: "Sesame seeds are tombstones for fallen condiments.",
    number: "008",
  },
  frywraith: {
    type: "OIL · GHOST",
    hp: 70,
    atk: 75,
    spd: 93,
    weird: 84,
    rarity: "common",
    flavor: "Salty, spectral, and somehow still warm.",
    number: "009",
  },
  milkspecter: {
    type: "CRT · SOUR",
    hp: 90,
    atk: 54,
    spd: 48,
    weird: 96,
    rarity: "rare",
    flavor: "The expiration date was a prophecy.",
    number: "010",
  },
  pizzoid: {
    type: "SLC · OVEN",
    hp: 84,
    atk: 81,
    spd: 60,
    weird: 86,
    rarity: "rare",
    flavor: "Pepperoni pupils track your every dodge.",
    number: "011",
  },
  sodasnarl: {
    type: "FIZ · RAGE",
    hp: 78,
    atk: 77,
    spd: 80,
    weird: 89,
    rarity: "common",
    flavor: "Shaken, not stirred — shaken by rage.",
    number: "012",
  },
  donutcreep: {
    type: "RNG · VOID",
    hp: 72,
    atk: 70,
    spd: 88,
    weird: 92,
    rarity: "common",
    flavor: "The hole in its center leads somewhere worse.",
    number: "013",
  },
  hotdogwraith: {
    type: "MST · BUN",
    hp: 85,
    atk: 83,
    spd: 52,
    weird: 80,
    rarity: "rare",
    flavor: "Mustard trails follow it like funeral incense.",
    number: "014",
  },
  jellophant: {
    type: "WBL · GHOST",
    hp: 68,
    atk: 56,
    spd: 64,
    weird: 97,
    rarity: "rare",
    flavor: "Wobbles through walls and your last nerve.",
    number: "015",
  },
  poptartgeist: {
    type: "CRST · HEAT",
    hp: 79,
    atk: 74,
    spd: 71,
    weird: 85,
    rarity: "common",
    flavor: "Frosting spells crackle when the toaster calls.",
    number: "016",
  },
  cornfiend: {
    type: "KRN · STALK",
    hp: 81,
    atk: 76,
    spd: 58,
    weird: 83,
    rarity: "rare",
    flavor: "Every kernel is an eye that never blinks.",
    number: "017",
  },
  ramenlich: {
    type: "BRTH · NOODL",
    hp: 77,
    atk: 68,
    spd: 62,
    weird: 94,
    rarity: "rare",
    flavor: "Steam rises from the cup like departing souls.",
    number: "018",
  },
  pretzelwraith: {
    type: "SLT · TWIST",
    hp: 83,
    atk: 71,
    spd: 75,
    weird: 87,
    rarity: "common",
    flavor: "Twisted into shape by cafeteria guilt.",
    number: "019",
  },
  wafflegeist: {
    type: "GRID · SYRUP",
    hp: 74,
    atk: 80,
    spd: 66,
    weird: 90,
    rarity: "common",
    flavor: "Syrup pools in its squares like trapped screams.",
    number: "020",
  },
};
